name: Issue Closed

on:
  issues:
    types:
      - closed

jobs:
  remove-state-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove started label
        if: contains(github.event.issue.labels.*.name, 'started')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["started"]
            })

      - name: Remove review label
        if: contains(github.event.issue.labels.*.name, 'review')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["review"]
            })
